ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS assignment_mode TEXT DEFAULT 'auto',
  ADD COLUMN IF NOT EXISTS assigned_by TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

